global:
  scrape_interval: "10s"

scrape_configs:
  - job_name: "python-app"
    static_configs:
      - targets:
        - app1:8000
        - app2:8000
  - job_name: "haproxy"
    static_configs:
      - targets: 
        - haproxy-exporter:9101
